<a href="https://colab.research.google.com/github/sagarladla/D2Ls_Deep_Learning-Pytorch/blob/master/2_1_Data_Manipulation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
x = torch.arange(12)
print(x)
print("Shape of x: ", x.shape)
print("Total number of elements: ", x.size())
# x.reshape((3, 4))
# use -1 to implicitly detect another dimension given one dimension
# x.reshape((-1, 4)) or next one
x = x.reshape(3, -1)
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])
Shape of x:  torch.Size([12])
Total number of elements:  torch.Size([12])
tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


In [0]:
y = torch.empty(2, 3)
print(y)
zeros = torch.zeros(2, 3, 4)
print(zeros, end="\n\n")
ones = torch.ones(2, 3, 4)
print(ones, end="\n\n")
randn = torch.randn(3,4)
print(randn, end="\n\n")

manx = torch.tensor([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(manx)

tensor([[7.7615e-36, 0.0000e+00, 1.6535e-43],
        [5.6052e-44, 1.5975e-43, 1.4153e-43]])
tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

tensor([[ 0.8963,  0.4863,  0.6249, -1.2303],
        [-1.1122,  0.0295, -0.5138,  0.3617],
        [ 1.2746, -0.2559,  1.2176, -1.2989]])

tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]])


In [0]:
x = torch.tensor([1.0,2,4,8])
y = torch.tensor([2,2,2,2,])
x+y,x-y,x/y,x**y # ** is exponentiation operator

torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [0]:
x = torch.arange(12, dtype=torch.float32).reshape(3,-1)
y = torch.tensor([[2.0,1,4,3],[1,2,3,4],[4,3,2,1]])
torch.cat((x,y), dim=0), torch.cat((x,y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [0]:
x == y
x.sum()

tensor(66.)

In [0]:
# Boradcasting : binary element wise operations on matrices of different dimensions
a=torch.arange(3).reshape(3,1)
b=torch.arange(2).reshape(1,2)
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [0]:
# Indexing
x[1,2]=9
# Slicing
x[:2,:] = 12
x

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [0]:
# Not saving memory
before = id(y)
y=y+x
id(y) == before

# Saving memory
z=torch.zeros_like(y)
print("id(z): ", id(z))
z[:]=x+y
print("id(z): ", id(z))

### or

print("id(x): ", id(x))
x+=y
print("id(x): ", id(x))

id(z):  140346485048808
id(z):  140346485048808
id(x):  140346485134392
id(x):  140346485134392


In [0]:
a=x.numpy()
b=torch.tensor(a)
type(a), type(b)

a=torch.tensor([3.5])
a
a.item() # torch tensor's function
int(a),float(a) # Python's inbuilt function

tensor([3.5000])