<a href="https://colab.research.google.com/github/sagarladla/D2Ls_Deep_Learning-Pytorch/blob/master/2_3_Linear_Algebra.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [0]:
# Scalars
x=torch.tensor([3.])
y=torch.tensor([2.])

x+y,x*y,x-y,x/y,x**y

(tensor([5.]), tensor([6.]), tensor([1.]), tensor([1.5000]), tensor([9.]))

In [0]:
# Vectors
x=torch.arange(4)
x[3]

len(x) # `Length of vector` is `dimension of vector`

4

In [0]:
A = torch.arange(20).reshape(5,-1)
A.T

# Symmetric matrix: B = B.T
B = torch.tensor([[1,2,3],[2,0,4],[3,4,5]])
print(B)
print(B.T)

B==B.T

tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])
tensor([[1, 2, 3],
        [2, 0, 4],
        [3, 4, 5]])


tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [78]:
X=torch.arange(24).reshape(2,3,4)
X

A=torch.arange(20, dtype=torch.float32).reshape(5,4)
B=A.clone() # Copy of A to B by allocating new memory
A,A+B
A*B # Hadamard product, elementwise multiplication of matrices

a=2
X=torch.arange(24).reshape(2,3,4)
X
a+X
(a*X).shape

torch.Size([2, 3, 4])

In [0]:
# Reducing sum ie dissolving of dimensions
x=torch.arange(4, dtype=torch.float32)
x,x.sum()

A.shape, A.sum()

A_sum_axis0=A.sum(axis=0)
print("Along axis 0: ", A_sum_axis0, A_sum_axis0.shape)

A_sum_axis1=A.sum(axis=1)
print("Along axis 1: ",A_sum_axis1, A_sum_axis1.shape)

A.sum(axis=[0,1]) # Same as A.sum()

# Mean or average
A.mean(), A.sum()/A.numel()

A.mean(axis=0), A.sum(axis=0)/A.shape[0]

Along axis 0:  tensor([40., 45., 50., 55.]) torch.Size([4])
Along axis 1:  tensor([ 6., 22., 38., 54., 70.]) torch.Size([5])


(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [0]:
# Non reducing sum ie keepdims=True

sum_A=A.sum(axis=1, keepdims=True)
sum_A

A/sum_A

A.cumsum(axis=0)

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

In [0]:
# dot product
y=torch.ones(4, dtype=torch.float32)
x, y

torch.dot(x,y), torch.sum(x*y) # elementwise multiplication & sum = dot product

(tensor(6.), tensor(6.))

- given data values in vector denoting <math xmlns="http://www.w3.org/1998/Math MathML"><mrow class="MJX-TeXAtom-ORD"><mi mathvariant="bold"><b>x </mi></mrow><mo>&#x2208;<!-- ∈ --></mo><msup><mrow class="MJX-TeXAtom-ORD"><mi mathvariant="double-struck"> R</mi></mrow><sup>d</sup></msup></b></math> and set of weights <math xmlns="http://www.w3.org/1998/Math MathML"><mrow class="MJX-TeXAtom-ORD"><mi mathvariant="bold"><b>w </mi></mrow><mo>&#x2208;<!-- ∈ --></mo><msup><mrow class="MJX-TeXAtom-ORD"><mi mathvariant="double-struck"> R</mi></mrow><sup>d</sup></msup></b></math>, then weighted sum of values in <b>x</b> w.r.t. <b>w</b> expressed as <b>x<sup>T</sup>w</b>. 

- When weights are `non -ve` & `w.sum()=1`, <em>"dot product expresses weighted average"</em>.

- After normalizing <b>x</b> & <b>w</b> both vectors to unit length, <em>"dot product expresses cosine of angle between them".</em>

In [0]:
A.shape, x.shape, torch.mv(A,x)

A, x

B=torch.ones(4,3)
torch.mm(A,B)

tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])

In [0]:
# l2 norm
u=torch.tensor([3.0, -4.0])
torch.norm(u)

# l1 norm
torch.abs(u).sum()

# Frobenius norm
X = torch.ones(4,9)
torch.norm(X)

tensor(6.)

# Norm properties
![Norm Properties](https://raw.githubusercontent.com/sagarladla/D2Ls_Deep_Learning-Pytorch/master/Norms/1_1.jpg)

# l<sub>2</sub> norms
![l2 norms](https://raw.githubusercontent.com/sagarladla/D2Ls_Deep_Learning-Pytorch/master/Norms/1_2.jpg)

# l<sub>1</sub> norms
![l1 norms](https://raw.githubusercontent.com/sagarladla/D2Ls_Deep_Learning-Pytorch/master/Norms/1_3.jpg)

# general/l<sub>p</sub> norms and Ferobenius norms
![general or lp norms & Frobenius norms](https://raw.githubusercontent.com/sagarladla/D2Ls_Deep_Learning-Pytorch/master/Norms/1_4.jpg)

In DL we do optimization problems: 
- <b>`maximize`</b> probability assigned to observed data,
- <b>`minimize`</b> distance between prediction & ground truth.

### Assigning vector representations to - words, articles, products, such that :

- `distance maximizes` among dissimilar items
- `distance minimizes` among similar items.

# Thus, more often objectives (components of DL algos) are expressed as *__norms__*.

In [0]:
# Exercises

# 1. (A.T).T = A // high school work
# A = torch.arange(12).reshape(4,-1)
# (A.T).T == A

# 2. A.T + B.T = (A+B).T
# B = torch.ones(4, 3)
# A.T + B.T == (A+B).T

# 3. Bcuz A = A.T. That's why A + A.T = always symmetric.

# 4. len(torch.tensor(dim=(2,3,4)))
# X = torch.arange(24).reshape(2,3,4)
# len(X)

# 5. Yes, len(X) always corresponds to certain axis of X. That axis is always outermost most axis, ie axis=0

# 6. Reason - Bcuz it is not a square matrix, ie rows != cols. A/A.sum(axis=1)
# 7. 
# 8. tensor.shape = (2,3,4)
# tensor containing two matrices of 3 x 4 each
# sum(axis=0), dimension = 3 x 4
# sum(axis=1) (rows), dimension = 2 x 4 x 1
# sum(axis=2) (cols), dimension = 2 x 3 x 1