<a href="https://colab.research.google.com/github/sagarladla/D2Ls_Deep_Learning-Pytorch/blob/master/2_5_Automatic_Differentiation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import torch

In [46]:
x = torch.arange(4. , requires_grad=True)
x.grad # Initially gradient whould be none.

# y calculated as function of vector x
y=2*torch.dot(x,x)
#y = scalar value

# gradient of y w.r.t to vector x
y.backward()

# gradient of `scalar` (y) w.r.t to `vector` (x) of `D` dimension, gives `vector` (x) of `D` dimension
x.grad

x.grad == 4*x

tensor([True, True, True, True])

<u>d</u>( 2 * __x__ * __x__ )<br>
d<b>x</b>

2 <u>d</u>(x<sup>2</sup>)<br>
&nbsp; dx

2 * 2 * x = __4 * x__


In [52]:
# if we want to calculate gradient of another value as function of `x`,
# we need to clear out all previous gradients,
# clears out all gradients of vector x
x.grad.zero_()

# u calculated as function of vector x
u = x.sum()

# gradient of u w.r.t to vector x
u.backward()

x.grad

tensor([1., 1., 1., 1.])

# Detaching computation

In [60]:
x.grad.zero_()
y=x * x
z = y * x
z.sum()
z.backward()
# y.grad

RuntimeError: ignored

`y` was calculated as function of vector `x`
--
`y` = `x` * `x`
--
`z` = `y` * `x` # we need to take `y` as constant instead of `y = x * x` ie, `z` = `x * x * x`
--
# to do so, we `detach()` `y` and store in new memory address, `u` = `y.detach()`
then compute, `z = u * x`
--

In [71]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z=z.sum()
z.backward()
x.grad == u

tensor([True, True, True, True])

In [72]:
# In above cell, y = x * x got computed
x.grad.zero_() # clearing out old gradients caluclated
y.sum().backward()
x.grad == 2 * x

tensor([True, True, True, True])

<u>d</u>( __x__ * __x__ )<br>
d<b>x</b>

<u>d</u>(x<sup>2</sup>)<br>
dx

= __2 * x__

# Gradient of python control flow

In [0]:
def f(a):
  b = a*2
  while b.norm().item() < 1000:
    b *= 2
    if b.sum().item() > 0:
      c = b
    else:
      c = 100 * b
    return c

In [79]:
a = torch.randn(size=(1,), requires_grad=True)
print(a)
d = f(a)
d.backward()
a.grad
a.grad == d/a

tensor([0.8804], requires_grad=True)
tensor([0.8804], requires_grad=True)


tensor([True])