<a href="https://colab.research.google.com/github/sagarladla/D2Ls_Deep_Learning-Pytorch/blob/master/2_6_Probability.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
%matplotlib inline
import torch
from torch.distributions import multinomial # for assignment of probabilities to events
import numpy as np

In [2]:
fair_probs = torch.ones([6])/6
multinomial.Multinomial(1, fair_probs).sample() # for 1 throw of die at a time
multinomial.Multinomial(10, fair_probs).sample() # for 10 thows of die at a time

tensor([2., 2., 0., 2., 3., 1.])

In [5]:
counts = multinomial.Multinomial(10, fair_probs).sample(sample_shape=(3,))
print(counts)
# ---------or---------
# PyTorch's Multinomial distribution doesn't offer the functionality
# for conducting multiple experiments at once. In such case we can always
# use numpy and later convert the ndarray to a torch tensor

# 3 people/group experimenting, each with 10 thows of die at a time
counts = torch.from_numpy(np.random.multinomial(10, fair_probs, size=3))
print(counts)


# thowing 1000 times a die
counts = multinomial.Multinomial(1000, fair_probs).sample().type(torch.float32)
# relative frequency is true estimate of probability
counts/1000

tensor([[2., 2., 0., 2., 2., 2.],
        [2., 2., 3., 1., 2., 0.],
        [0., 1., 4., 2., 3., 0.]])
tensor([[0, 3, 3, 1, 2, 1],
        [4, 1, 4, 0, 1, 0],
        [1, 0, 3, 1, 3, 2]])


tensor([0.1610, 0.1560, 0.1700, 0.1800, 0.1780, 0.1550])

# `THIS PART IS SKIPPED!!!`

In [0]:
# Visualizing 500 people/group exprimenting, each drawing 10 samples
counts = torch.from_numpy(np.random.multinomial(10, fair_probs, size=500)).type(torch.float32)
print(counts)

cum_counts = counts.cumsum(axis=0)

tensor([[1., 3., 1., 1., 1., 3.],
        [2., 1., 3., 1., 1., 2.],
        [4., 2., 0., 2., 1., 1.],
        ...,
        [3., 0., 3., 3., 1., 0.],
        [3., 1., 3., 1., 1., 1.],
        [0., 0., 4., 3., 0., 3.]])

# AXIOMs OF PROBABILITY THEORY...

# `FuNc pRoBaBiLiTY():` maps a set to real value

# Joint Probability

> Probability of 2 events occuring : <h1>`simultaneously`</h1>
  > eg - P(A, B) = `P(A) and P(B)` // `P(A) Λ P(B)` // `P(A) * P(B)`

> ie, `P(A, B) < P(A) or P(B)`







# Conditional Probability
 > # 0 <= [ P(A, B) / P(A) ] <= 1

 > # P(B | A) - `P(B)` given "`P(A)` - which has already occured!!!"

# Bayes Theorem
## Multiplication rule
> # `P(A, B) = P(B | A) * P(A)`
> # `P(B, A) = P(A | B) * P(B)`

# `A` & `B` are conditional random variables

